Ignore failure to install ic-cdk-optimizer
When installing the ic-cdk-optimizer in CI/CD without the `--force` flag
we get the following output:

```shell
[1/3] 🔨 Compiling Python...

💣 Unable to install dependency "ic-cdk-optimizer"

    Updating crates.io index
error: binary `ic-cdk-optimizer` already exists in destination
Add --force to overwrite

💀 Build failed
```

When using `--force` to install the optimizer, all dependencies of
ic-cdk-optimizer are re-installed every time. This means that step 1 of
the script jumps from 1 second up to 90 seconds on subsequent installs.

Rather than force everyone to wait for all dependencies to re-install
each time they run `dfx deploy`, we now assume that a failure means the
binary was already installed.

## Why does it fail?

It seems like the cache in CI/CD doesn't contain everything it needs.
Some minimal research makes me believe we need to cache:

- ~/.cargo/.crates.toml
- ~/.cargo/.crates2.json

See:

https://www.reddit.com/r/learnrust/comments/lexewr/the_difference_in_behaviour_when_running_cargo/